[package]
name = 'predefined_chains'
edition = { workspace = true }
authors = ["Grandine <info@grandine.io>"]

[lints]
workspace = true

[dependencies]
duplicate = { workspace = true }
genesis = { workspace = true }
hex-literal = { workspace = true }
ssz = { workspace = true }
types = { workspace = true }

[dev-dependencies]
std_ext = { workspace = true }
test-case = { workspace = true }
