[package]
name = 'ssz_derive'
edition = { workspace = true }
authors = ["Grandine <info@grandine.io>"]

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
darling = { workspace = true }
easy-ext = { workspace = true }
itertools = { workspace = true }
proc-macro-crate = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
